runtime: python37handlers:
application: stone_cold_props

- url: /static
  static_dir: static/# This handler routes all requests not caught above to the main app.

- url: /.*
  script: auto# [END django_app]