# Generated by Django 2.2.7 on 2019-11-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('first_name', models.CharField(blank=True, db_column='First_Name', max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Last_Name', max_length=20, null=True)),
                ('income', models.DecimalField(blank=True, db_column='Income', decimal_places=2, max_digits=8, null=True)),
                ('ssn', models.CharField(db_column='SSN', max_length=11, primary_key=True, serialize=False)),
                ('account_balance', models.DecimalField(blank=True, db_column='Account_balance', decimal_places=2, max_digits=8, null=True)),
                ('building_id', models.DecimalField(blank=True, db_column='Building_ID', decimal_places=0, max_digits=4, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=12, null=True)),
            ],
            options={
                'db_table': 'Tenant',
            },
        ),
    ]
