# Generated by Django 2.2.7 on 2019-11-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'managed': False},
        ),
    ]
